// <auto-generated />
using HomeLibraryManager.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeLibraryManager.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220627174026_AddingMoreFieldsToBook")]
    partial class AddingMoreFieldsToBook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("HomeLibraryManager.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleBookId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ISBN10")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ISBN13")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFirstEdition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Large")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrintNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Small")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmallThumbnail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
